version: "3.9"
services:
  mainnetwork:
    image: alpine:3.14
    command: ["tail", "-f", "/dev/null"]
  db:
    image: postgres:14-alpine
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./database/script:/script:ro
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  backend:
    image: python:3.9
    working_dir: /app/backend
    command: ["./start.sh"]
    volumes:
      - ./:/app:delegated
      - ./i18n:/app/i18n:delegated
    environment:
      - DB_SCHEMA=partos_pat
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
      - DEBUG=True
      - SECRET_KEY=secret
      # env vars for coveralls
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN:-}
    depends_on:
      - db
  frontend:
    image: akvo/akvo-node-18-alpine:20230831.105309.b9593b7
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
      - ./i18n:/app/i18n:delegated
    working_dir: /app
    depends_on:
      - backend
volumes:
  pg-data:
